# Generated by Django 2.2.3 on 2019-07-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mob_no', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('u_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('p_word', models.CharField(max_length=20)),
                ('cp_word', models.CharField(max_length=30)),
            ],
        ),
    ]
